name: concierge

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 18080
  adminConnectors:
    - type: http
      port: 18081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    com.phonepe.concierge: DEBUG
  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"

aerospikeConfig:
  namespace: test
  hosts:
    - host: localhost
      port: 3000
  username:
  password:
  maxConnectionsPerNode: 10
  timeout: 1000
  retries: 3
  sleepBetweenRetries: 5
  maxSocketIdle: 4140
  threadPoolSize: 512